### ISSUE TITLE
why not output the mse in the result? for performance?

### ISSUE THREAD

**Issue by zachzh** [benfred/implicit#11]

**Comment by benfred** [comment]
MSE can be pretty easily calculated at run time - and seems like it could be a helpful diagnostic to check convergence. I'll see about adding sometime soon

**Comment by zachzh** [comment]
Yes, it really help. Hope to see that :)

**Comment by benfred** [comment]
I've added a function to calculate MSE here https://github.com/benfred/implicit/commit/da1a7fa5cdf845d99b6785426c3831beed89a0c8

I've left off by default since there is still a small performance penalty for calculating this, but if you pass 'calculate_training_loss=True' to alternating_least_squares this will calculate the loss at each iteration and log it out
