### ISSUE TITLE
Does not work when deployed on AWS Lambda

### ISSUE THREAD

**Issue by srcolinas** [benfred/implicit#136]
I created a Flask app which uses Implicit and I am trying to deploy it as a service on AWS Lambda using [Zappa]((https://github.com/Miserlou/Zappa)). Nonetheless I can't make it work and I am pretty sure the issue only comes up when import implicit. I have already written the issue in the Zappa repository, but I wonder whether you may have encounter a limitation or additional step necessary to make it work on AWS Lambda.

Related links:
* [Zapa repository](https://github.com/Miserlou/Zappa)
* [Issue posted on the Zappa repo](https://github.com/Miserlou/Zappa/issues/1558)

**Comment by ita9naiwa** [comment]
I don't know Zappa, but it will be very helpful if you give error logs if any.

some other story:
I think I was in your situation. How to get recommender model(using Implicit) work on AWS?

I chose these two alternatives. Considering these might be helpful for you.

1. You shall choose [aws-lambda-numpy](https://github.com/vitolimandibhrata/aws-lambda-numpy) to recommend items (recommending items to users is basically similarity calculation.)
Train user/item vectors using Implcit(or any other frameworks) and upload these vectors on S3 for AWS lambda function to read it.

2. (1) is good, but The  Lambda has very serious problem called [Cold-start problem](https://read.acloud.guru/cold-starting-lambdas-2c663055589e).
So, You may consider launching EC2 instance to handle recommendation stuffs.

I'm using both methods for various purposes, anyway.

**Comment by srcolinas** [comment]
Thanks for your reply, I actually consider that your first alternative is quite clever. I leave the issue open in case there is an alternative that would just work using a pickled model.

**Comment by benfred** [comment]
@srcolinas I'm not familiar with zappa, what's the error message that happens when you try to run this? 

I imagine that the difficulty is in getting the dependencies for implicit installed. IIRC, you only get like 50mb or so for all your code when running on aws lambda - and I'm wondering we're blowing through it with numpy/scipy etc.

Also - I think that staying away from pickle is probably wise for loading/saving models. One of the things that I want to do is add support for serialization of models - and I'm thinking either h5py or apache arrow as a format.

The advantage of h5py is that I'm using it already here for loading sample datasets, but I think that arrow w/ plasma storage might actually work better - especially for situations like yours where you are serving requests using flask (in which case it would be basically instant to load, since can just use mem-mapped storage of files that are already swapped in).

**Comment by srcolinas** [comment]
@benfred  the errors showed by Zappa are not very informative, it basically says that there was an error when attempting to connect to the generated API Gateway.  

I used @ita9naiwa 's suggestion and saved only the `item_factors` and `user_factors` attributes. Now I can import them from lambda since they only need numpy to work, which make Zappa and AWS Lambda work as expected (perhaps your hint was right).

Now that you mention the serialization format, I would like to get some advice for loading the arrays, which are stored in S3, into AWS Lambda. I used pickle in this case because it was fast and I could deserialize it easily by reading the bytes from `boto3.resource('s3').Object(...).get()`.

I will close this issue since I no longer think it is an issue with implicit, but rather a restriction of AWS Lambda or an issue of Zappa.

Thanks!
