### ISSUE TITLE
approximate_als not in init

### ISSUE THREAD

**Issue by SteveOf** [benfred/implicit#144]
Hi. More of a question but is it on purpose that approximate_als is not included in __init__.py (due to nmslib dependencies for instance)?

**Comment by benfred** [comment]
There is no good reason why it isn't included - the nmslib/faiss dependencies aren't imported until you create the classes so it should be ok to import in the module ```__init__```

I am thinking about refactoring the approximate_als code quite a bit though - I want to make it so that we reuse this code for the BPR model too. I'm not sure if that will change how this is imported yet ...

**Comment by benfred** [comment]
I added the import here https://github.com/benfred/implicit/commit/6a2fed489d8ee43bef28b98546adde0f10cdb802 - it will be in the next release
