### ISSUE TITLE
Installing from sources

### ISSUE THREAD

**Issue by alexeygrigorev** [benfred/implicit#15]
I'm trying to install the package from sources with the following command:

    python setup.py install

However, when I `import implicit` I get the following error:
```

In [1]: import implicit
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-9eae7608d57c> in <module>()
----> 1 import implicit

/home/agrigorev/soft/implicit/implicit/__init__.py in <module>()
----> 1 from .implicit import alternating_least_squares
      2 
      3 __version__ = '0.1.5'
      4 
      5 __all__ = [alternating_least_squares, __version__]

/home/agrigorev/soft/implicit/implicit/implicit.py in <module>()
      4 import os
      5 import logging
----> 6 from . import _implicit
      7 
      8 log = logging.getLogger("implicit")

ImportError: cannot import name '_implicit'
```

I assume this indicates that there was a problem with building the cython source. 

What is the correct way of installing the library from sources? I'm running anaconda3 with python 3.5 under ubuntu.

**Comment by benfred** [comment]
Looking at the stack trace, and it seems like you are picking up the implicit source code (/home/agrigorev/soft/implicit/implicit/implicit.py) - rather than the built version you installed which should be in a directory like anaconda3/lib/python3.5/site-packages/implicit. I'm guessing that your current working directory is /home/agrigorev/soft/implicit when calling this?

Can you try installing with 'python setup.py develop' ?  This will set up the built cython modules inside your local source tree . Alternatively you could try importing from a different directory

**Comment by alexeygrigorev** [comment]
I'm sorry - yes, you are right, the issue is that I was in the installation directory when checking... If I cd to a different directory, everything works. 

Thanks for helping.
