### ISSUE TITLE
Allow specifying gcc -march parameter in setup.py 

### ISSUE THREAD

**Issue by smartnose** [benfred/implicit#16]
The logic in setup.py fallbacks to '-march=native' if anaconda is not detected. This creates a problem for our Jenkins build. Can we update the build commands to allow custom CPU types?

**Comment by benfred** [comment]
Is the issue that your Jenkins box has a newer CPU (or different architecture) than your deployment boxes? Or is it just not building at all on your jenkins box?

I haven't actually tested out how much of a performance hit removing this flag would cause - I doubt its that large (since most work here should be pushed down to BLAS/LAPACK libraries). I'll play around with it on the weekend and if the performance difference is negligible I can remove . Alternatively specifying something like '-march=core -mtune=generic' should work for you and still enable a bunch of optimizations.

**Comment by smartnose** [comment]
Thanks for responding.
The problem is that our Jenkins box has an older CPU (pentium-m) than my deployment. The build  fails at the step of installing implicit. The build works both locally and on the production cluster.
We are currently solving the problem by creating prebuilt wheels of implicit package to avoid gcc compiling altogether. Do you have plan to publish wheels of various CPU architectures to PyPI? That might be another way to solve the problem.

**Comment by benfred** [comment]
I tested out a bit today - and I didn't notice any decreased performance without the '-march=native' compile options.  Removed in the last commit there
