### ISSUE TITLE
Dynamically detect CUDA availability

### ISSUE THREAD

**Issue by mdekstrand** [benfred/implicit#174]
It'd be useful in my environment to dynamically detect whether CUDA is actually available when Implicit has been built with CUDA.

Our cluster has some nodes with GPUs and some without. As it is, my experiment code has logic to detect which queue I submitted an experiment to and set `use_cuda` appropriately; falling back to non-CUDA operation (possibly with a warning?) if CUDA is compiled but not available at runtime would simplify driver code operating in heterogeneous environments.

**Comment by lethaiq** [comment]
I think this is incorporated in the latest version of the library.

**Comment by benfred** [comment]
This is done with #518 - and will be in the next release. Sorry for the delay in getting this 

The next release will also include some breaking API changes - and I'm wondering if this will affect the shims in lenskit ? #481 has details of the changes, but the big ones are that we're changing model.fit to take a user/items sparse matrix (instead of a item/users sparse matrix) and that we're also changing the return value type from the recommend/similar_items methods.

**Comment by mdekstrand** [comment]
@benfred thanks! In the next release of LensKit (0.14), I am splitting the various shims into their own packages (implicit's is [here](https://github.com/lenskit/lenskit-implicit)), which will hopefully ease maintenance a bit. Can update that so it uses 0.5 easily enough, I think.

My only concern is that the current (and older) versions of LensKit don't have a max version bound on the `implicit` dependency, so they might pull in the newer version and break. I can push an update to the `conda-forge` package that puts in the max bound easily enough though.
