### ISSUE TITLE
CosineRecommender isn't pickable

### ISSUE THREAD

**Issue by marinkreso** [benfred/implicit#191]
I created _CosineRecommender_ model and fitted it to my dataset. When I try to pickle the fitted model with `pickle.dumps(model)` I get `TypeError: no default __reduce__ due to non-trivial __cinit__` error in because of NearestNeighboursScorer.__reduce_cython__() method. 

Pickling _AlternatingLeastSquares_ model works great. 

Is there a way to pickle _CosineRecommender_ model or to use some other serialization method for serializing this object/model?

**Comment by mohjeih** [comment]
I have encountered recently the same issue as you. My quick solution which definitely is not the best one is as follows: assign model scorer to a temporary variable, assign 0 to the model scorer, pickle the fitted model, and finally assign the value of the temporary variable to the model scorer. Hopefully, this issue will be fixed in the future versions.

**Comment by benfred** [comment]
This PR adds support for pickling knn models: https://github.com/benfred/implicit/pull/229

**Comment by benfred** [comment]
fix is in v0.3.9

**Comment by marinkreso** [comment]
Hi,

Thanks for great news.

Best regards,
Marin Krešo


sub, 13. srp 2019. 18:52 Ben Frederickson <notifications@github.com> je
napisao:
