### ISSUE TITLE
Module 'implicit' has no attribute 'lmf'

### ISSUE THREAD

**Issue by ioulaki** [benfred/implicit#287]
I installed the latest release today using 'pip install implicit' and wanted to use Logistic MF. However, I get the following error: Module 'implicit' has no attribute 'lmf'
And, indeed, the module contains only the attributes regarding ALS and AALS, BPR, NN, Recommender Base, Utils.

**Comment by ita9naiwa** [comment]
Try install via pip

I forgot to update implicit on Conda...

**Comment by ioulaki** [comment]
Thanks for the quick response!
I installed it using pip and can use the lmf attribute outside conda, but since I'm using Spyder it would be more useful to have the latest update in Conda as well. Will you be updating it there as well?
Once again, thank you for taking the time to reply so quickly !

**Comment by ita9naiwa** [comment]
The owner didin't give me the permission to upload conda yet. thus it will take some times.
I'll ask the owner, Ben.

**Comment by thisisfruit** [comment]
Hi @ita9naiwa,
Due to some reasons I can't install this package via pip. I've installed implicit via conda and checked its version(0.3.7, not the latest one 0.4.0) and encountered the same question on Windows. Any solutions to solve this error?
<img width="303" alt="implicit擷取" src="https://user-images.githubusercontent.com/42990686/78096371-f4475800-740b-11ea-9367-6cb455336804.PNG">

**Comment by ita9naiwa** [comment]
@thisisfruit Why don't you clone this reopsitory and install using `python setup.py install`

**Comment by thisisfruit** [comment]
@ita9naiwa WOW! Thank you and I will try it!
