### ISSUE TITLE
_check_fit_errors can't be found in Alternating Least Squares

### ISSUE THREAD

**Issue by tRosenflanz** [benfred/implicit#391]
<img width="544" alt="Screen Shot 2020-08-20 at 12 34 29 PM" src="https://user-images.githubusercontent.com/25041325/90805728-a3b09880-e2e1-11ea-801f-704ebc96e491.png">

I think this tries to use hidden method from parent class that causes naming issues 

https://github.com/benfred/implicit/blob/234f905e81bbf5f24afeff68da95342d5f08225c/implicit/als.py#L189

**Comment by benfred** [comment]
Did you pull recently ?  If so you need to rebuild the cython files.

I think this change adds this method: https://github.com/benfred/implicit/commit/7be85b2f610ae9fa032deb6e56fcbb2ca2a2b7e6 , and since the base class is cython (but the derived class is python) - you need to recompile to pick up the new method in the base.

**Comment by tRosenflanz** [comment]
This is using Docker so maybe it wasn't correctly recompiling all the files. Let me try different builds or at least maken a minimal dockerfile to reproduce error

**Comment by tRosenflanz** [comment]
For some reason `pip install git+https://github.com/benfred/implicit.git` wasn't installing Cython so files were not recompiled. After adding installing it manually it works now

**Comment by benfred** [comment]
Fwiw - it looks the recommender_base.cpp file wasn't regenerated from cython. This was also causing issues with CI . I fixed it here https://github.com/benfred/implicit/pull/397
