### ISSUE TITLE
ALS Scores clarification and definition

### ISSUE THREAD

**Issue by kmcmearty** [benfred/implicit#399]
I've searched all over the Implicit docs and around the internet to understand what the scores are for the ALS recommender. Specifically, I am running the LastFM example and want to understand the scores for the recommended artists and similar artists.

In the documentation, the `recommend()` method for ALS describes: "Calculates the N best recommendations for a user, and returns a list of itemids, score." This indeed returns a list of scores, but I'm not sure... is the 1st recommended item the best item?

In the paper Collaborative Filtering for Implicit Feedback Datasets, Hu et al. writes "Lower values of rank are more desirable, as they indicate ranking actually watched shows closer to the top of the recommendation lists. Notice that for random predictions, the expected value of rank ui is 50% (placing i in the middle of the sorted list). Thus, rank > 50% indicates an algorithm no better than random." ..... this is on page 6.

The best explanation I could find was on this article:
https://stats.stackexchange.com/questions/446814/how-to-interpret-recommender-scores-in-implicit-matrix-factorization

----------------------------------------------------------------------------------------------------------------------------------------

Maybe I am reading the paper incorrectly but it seems like the author wrote lower scores are better? But the statsoverflow mentions higher scores are better? Intuition leads me to believe the higher scores for the lastFM examples are better. 

- So my question is, are higher or lower scores better?

- What do scores over 1 mean?

- What do the scores mean? Would it be possible to get an explanation / discussion in the _implicit_ docs?

**Comment by benfred** [comment]
Scores for generating recommendations for a user are different from the scores returned from the similar artists.

Scores for the recommendations are the predicted value from the model for the given user and item. Higher values are better. Scores over 1 can happen since we're applying a least squares regression for each item/user on whether the user has interacted with the item (with a Pui of 1). Since this is a linear regression the scores aren't constrained to be within any bounds. Values much over 1 usually indicate that you need to lower the confidence values passed to the model though. The rank values you read about in the paper are different from the scores here - and would match up with the position in the sorted list instead of the scores that we are returning.

Calculating similar artists is just done by using cosine distance in between the learned item factors. Higher values are still better - but shouldn't ever be over 1 because of how cosine distance works.

**Comment by kmcmearty** [comment]
@benfred Thank you very much for explaining - makes more sense to me . 

1. Is there any way I could contribute some writing to Github or Implicit docs to help others understand the scores better?

2. In you're last sentence you mentioned that the similar items / users uses cosine which shouldnt result in an score greater than 1. I used youre similar artist function and swapped out `similar_items()` with `similar_users()` to find similar users. I have values greater than 1 so there must be something wrong. Do you have any suggestions to correct this?

`   
 
    purchases = purchases.tocsr()

    model.fit(purchases)
    
    user_count = np.ediff1d(purchases.indptr)
    
    to_generate = sorted(np.arange(len(customers)), key=lambda x: -user_count[x])
    
    similar_data = []
    with tqdm.tqdm(total=len(to_generate)) as progress:
            for cusmid in to_generate:
                cusm = customers[cusmid]
                for other, score in model.similar_users(cusmid, 11):
                    data = (cusm, customers[other], str(score))
                    similar_data.append(data)
                progress.update(1)
    
    df = pd.DataFrame(similar_data, columns =['cusm1', 'cusm2', 'score'])`
