### ISSUE TITLE
Make it possible to configure algorithm to return items 'liked' by the user?

### ISSUE THREAD

**Issue by vhfmag** [benfred/implicit#40]
I've been using this library for building a recommender system where items already consumed ('liked') shouldn't be hidden, so I had to download the library and recompile it to not filter them out.

How does it sound to expose a named parameter for disabling that filtering? I could implement it...

**Comment by benfred** [comment]
It makes sense to add that, if you want to put a PR together that would be awesome!

As a short term hack, you could pass a user_items matrix with an empty row for the user - but that isn't ideal.

**Comment by vhfmag** [comment]
I'm on it!

**Comment by vhfmag** [comment]
Done!

**Comment by ita9naiwa** [comment]
I think It might be also great that factor based model can recommend items without user-item matrix because the model do not require to search user-item matrix to find already liked items for an user.

**Comment by lautjy** [comment]
Hmm.. This PR: https://github.com/benfred/implicit/commit/fd984bc251e468e092ddf2bc7395127c21336482

implements NOT filtering out the liked items. Hence `.recommend(filter_already_liked_items=False)` returns also the ones user likes.

This is the line in master branch for reference:
https://github.com/benfred/implicit/blob/ed4fb0ae3d62972b956d7c94d495d198ec6185fe/implicit/recommender_base.py#L148

So is it possible to close this issue, and *perhaps* pop out a new build to PyPI @benfred ?

Would really salt my butter to get this feature straight from pip install, instead of monkey patching!!
(sorry for pinging if you are too busy)

**Comment by benfred** [comment]
@lautjy I've uploaded 0.3.7 to pypi!
