### ISSUE TITLE
Negative values in user and item factors

### ISSUE THREAD

**Issue by pkasar** [benfred/implicit#410]
I am seeing a lot of negative values in factors.
Since we are only using positive scores based on user/item purchase history, I am wondering what is causing negative values for latent factors.
Also is it possible to round the numbers. I am seeing scientific notation like -2.305012313134211e-.06
Thanks

**Comment by ita9naiwa** [comment]
I know only for factor-based recommenders (ALS, BPR, and LMF)

In BPR and LMF, negative values are ignored and treated as normal negative feedback.

for ALS, it is treated as negative feedbacks, with the confidence of absolute value of that negative value.

**Comment by benfred** [comment]
@pkasar its ok to see negative values in the learned factors - we're not doing non-negative matrix factorization here, so the learned values can be negative.

**Comment by pankaja0285** [comment]
I am unable to compute vector norms as I am getting the following error that * is not supported. Part of my code is
`quantities = list(data['quantity'].astype(float))  #.astype(int))

# Get the rows and columns for our new matrix
users = list(data['user_id'])   #.astype(int))
article_list = list(data['art_id'])   #.astype(int))

# Contruct a sparse matrix for our users and items containing number of quantities
# data_sparse = sparse.csr_matrix((quantities, (rows, cols)), shape=(len(users), len(article_list)))
sparse_item_user = sparse.csr_matrix((quantities, (article_list, users)))
sparse_user_item = sparse.csr_matrix((quantities, (users, article_list)))

model_2 = implicit.als.AlternatingLeastSquares(factors=20, regularization=0.1, iterations=20)
# Calculate the confidence by multiplying it by our alpha value.
alpha_val = 15
data_conf_2 = (sparse_item_user * alpha_val).astype('double')

# Fit the model
model_2.fit(data_conf_2)
# Get the user and item vectors from our trained model
user_vecs = model_2.user_factors
item_vecs = model_2.item_factors

#---------------------
# FIND SIMILAR ITEMS
#---------------------

# Find the 10 most similar to Jay-Z
item_id = 200 #Jersey top
n_similar = 10

# Calculate the vector norms
item_norms = np.sqrt((item_vecs * item_vecs).sum(axis=1))
`
![implicit_vec_norm_calc_err](https://user-images.githubusercontent.com/54913075/162836100-f7d199c8-7fb9-49e5-b529-94a2ab67d1c3.png)


Please advise.

**Comment by benfred** [comment]
@pankaja0285 The GPU models have factors stored in their own class - and can't be accessed directly like you're doing here. You can convert to numpy with `item_vecs = model.item_factors.tonumpy()` . 

Having said that, it sorta looks like you're trying to compute the top-N items from these. Have you considered using the `model.similar_items` or `model.recommend` functions instead of doing this yourself? This can be quite a bit more efficient than doing this in numpy, since we have an optimized top-k code built into the library.

**Comment by pankaja0285** [comment]
I understand what you are saying @benfred  - the reason I was doing is because this particular implementation mentions that in order to speed up to do so. Just for your reference I am including the article URL [https://medium.com/radon-dev/als-implicit-collaborative-filtering-5ed653ba39fe](https://medium.com/radon-dev/als-implicit-collaborative-filtering-5ed653ba39fe)
and please have a look at the section titled **_Even faster implicit with implicit!_**

..Incidentally the author of that article quotes you as well... :) ..

Can you please let me know how I should implement that section. Thanks in advance.

**Comment by benfred** [comment]
@pankaja0285  I would follow this tutorial: https://github.com/benfred/implicit/blob/main/examples/tutorial_lastfm.ipynb

**Comment by pankaja0285** [comment]
@benfred in your notebook in the section **_Making batch recommendations_** you have provided an example for an array of users, my question is the ids return are they artist - ids and the corresponding score?

**Comment by benfred** [comment]
> in your notebook in the section Making batch recommendations you have provided an example for an array of users, my question is the ids return are they artist - ids and the corresponding score?

Yup - the ids are for the items. There is one row per user in the input batch, and each row has the top 10 ids for each item for that user.


> also, in my case I have to do batch recommendations for about a million customers. Will this block of code in the Making batch recommendations handle in a notebook for e.g. on Colab or kaggle. Or should I do in batches of say 100,000 or something like that?

The .recommend call will batch for you - you can just call with all 1 million users

> in my case the user and artist - equivalent features are basically customers and articles, where in the customer id is a UUID, so is the article id - so I have created unique integer ids starting from 1.
> I would like to know how to situate my data for e.g. the sparse matrix namely artist_user_plays, in your notebook example...
Please let me know, if you have any suggestions so I can make things better and not re-invent the wheel or make it worse.

I'm not quite sure what you're asking - are you having issues turning string UUID's for the users/items into a sparse matrix? If so I have some example code in going from a dataframe of string users/items to a sparse matrix in this blog post https://www.benfrederickson.com/matrix-factorization/ .
