### ISSUE TITLE
values of item_user matrix

### ISSUE THREAD

**Issue by tangzhy** [benfred/implicit#414]
When we fit a model on item_user matrix, the description of the value in the matrix is as follows:

'''
item_user (csr_matrix) – A matrix of shape (number_of_items, number_of_users). The nonzero entries in this matrix are the items that are liked by each user. The values are how confident you are that the item is liked by the user.
'''

While the original paper having introduced implicit modeling suggested that `c_ui = 1 + alpha * r_ui`.  For the zero entries, the paper  still assigned minimal confidence (which is 1 in this case). Besides, the paper stated clearly that optimization should account for all possible u, i pairs and thus resolve to ALS for solution.

I'm confused how we shall properly set the values of matrix since the paper converted the sparse matrix into dense.

Say we have a matrix stored the raw observed data where each r_ui represents some frequency:

```
[[1, 0, 4, 5],
[2, 0, 8, 0], 
[3, 0, 12, 6]]
```

Can I apply some transformation such as `c_ui = 1 + alpha * r_ui` to it and feed it to model?

That seems not ok since in production environment my data scales up to billions easily and the matrix is dense?

Any advice on how to transform the toy data?

**Comment by benfred** [comment]
You want to keep the input matrix sparse or this won't work properly. 

Missing entries in the matrix are assumed to be to P_ui = 0 and C_ui = 1. Non-zero entries in the matrix have P_ui = 1 and the confidence as whatever the matrix value is.

If you want to add a constant value, you should only do this to the non-zero items of the matrix:

```python
ALPHA = 3.0

m = scipy.sparse.csr_matrix([[1, 0, 4, 5],
[2, 0, 8, 0], 
[3, 0, 12, 6]]
)
m.data  = 1 + ALPHA * m.data
```
(since the missing values all have a default confidence of 1, and R_ui is 0 in this case this transform is still all good).

However, I'd probably just scale things directly  (like ```m.data *= alpha``` ) instead of adding a constant.

**Comment by tangzhy** [comment]
Thanks!
