### ISSUE TITLE
recalculate_user parameter in the recommend() of the als.py

### ISSUE THREAD

**Issue by meidata** [benfred/implicit#42]
Hi Ben,

Thanks for the awesome library, i am using the library to create a recommender system.

I am trying to implement my own version of returning the liked items by the user, so can i ask you what do the recalculate_user parameter in the recommend() do in the als.py? 

Thank you in advance!

Meiyi

**Comment by jbochi** [comment]
`recalculate_user` allows you to update user's latent factors if the confidence matrix has changed since the training. You can use this to generate recommendations to users that were not in the training set too. I mentioned this feature here: https://medium.com/@jbochi/recommending-github-repositories-with-google-bigquery-and-the-implicit-library-e6cce666c77

**Comment by meidata** [comment]
Thanks Juarez, your blog is very useful!

So to summarise,
if you set recaluculate_user = True, it could be :

1. the user not in the training set (new user)
2. the user who is in the training set but consumes more items (new items)

In your blog, you set the confidence = 40, can i ask how you choose the value in this parameter?

Super Thanks,

Meiyi

**Comment by jbochi** [comment]
Glad you find it useful, Meiyi. 40 was the value used in the original paper "Collaborative Filtering for Implicit Feedback Datasets" paper, but you should definitely do some kind of evaluation to pick the best value or weighting scheme for your dataset.

**Comment by meidata** [comment]
Thanks Juarez!!
