### ISSUE TITLE
Train_Test_Split from custom dataset

### ISSUE THREAD

**Issue by pdavis156879** [benfred/implicit#430]
Hi!

I'm trying to use a custom dataset with implicit, unfortunately, the existing guides always rely on importing pre-formated datasets hence not very helpful.

Consider the following transformations, based on the single example I could find:

```
data = some_data.copy()
data['product'] = data['product'].astype('category')
data['user'] = data['product'].astype('user')

data['product'] = data['product'].cat.codes
data['user'] = data['user'].cat.codes

train, test = implicit.evaluation.train_test_split(data)
```

Yields the following error:
`AttributeError: 'DataFrame' object has no attribute 'tocoo'
`

I assume this happens due to it not being a sparse matrix. Question is, how should I transform the data so I pass it into the function? Unfortunately using scikit-learn's train_test_split results in not being able to use the evaluation metrics; my guess is because some products/users are only appearing in one of the sets.

**Comment by markdouthwaite** [comment]
Hey @pdavis156879! 

You can create a sparse matrix with something like:

```python
import numpy as np
import scipy.sparse as sp

... # your stuff

users = data["user"].values
products = data["product"].values

ratings = np.ones_like(users, dtype=float)

mat = sp.coo_matrix((ratings, (users, products)))

train, test = implicit.evaluation.train_test_split(mat)
```

The [scipy docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_matrix.html#scipy.sparse.coo_matrix) give more information on the coo_matrix API, if you're interested.

Let me know if that helps.

**Comment by igorkf** [comment]
@markdouthwaite do you now if:   
If I use `train_test_split` from `sklearn` to split my data (list of dicts having user, item, rating), and I use `train_test_split` from `implicit.evaluation` to split my sparse matrix, should we have the same users and items in both cases?     
I ask this because when I evaluate the model in validation data, I have to map each user to a index. If the two splits are equal, how can I get the users or items slicidng the sparse matrix?

**Comment by benfred** [comment]
@igorkf 

> If I use train_test_split from sklearn to split my data (list of dicts having user, item, rating), and I use train_test_split from implicit.evaluation to split my sparse matrix, should we have the same users and items in both cases?

the function in implicit doesn't split user or items - it splits the user/item interactions. That is, instead of removing rows(users) or columns (items) from the sparse matrix - it removes values from the sparse matrix, so the sparse matrices returned will have the same shape as the input.

The code from @markdouthwaite is great for transforming from a dataframe to a sparse matrix,
