### ISSUE TITLE
WARNING:root:Annoy isn't installed

### ISSUE THREAD

**Issue by innjoshka** [benfred/implicit#46]
all the time I try to use example script lastfm.py I get the error

python implicit_argparser.py --input=usersha1-artmbid-artname-plays.tsv 
WARNING:root:Annoy isn't installed
Traceback (most recent call last):
  File "implicit_argparser.py", line 155, in <module>
    cg=args.cg)
  File "implicit_argparser.py", line 97, in calculate_similar_artists
    model.fit(plays)
  File "/Users/Kakadu/anaconda/lib/python3.6/site-packages/implicit/annoy_als.py", line 78, in fit
    self.cosine_index = annoy.AnnoyIndex(self.item_factors.shape[1], 'angular')
NameError: name 'annoy' is not defined

Where can I get Annoy? P.S I use MacOS
by the way I used model=als by default and even in this way I get the error with Annoy that can be seen in Traceback , be glad to see a reasonable reply

**Comment by benfred** [comment]
`pip install annoy` will download and install the annoy library.

I didn't specify this as a dependency, mainly because when I first tried it failed to install on windows. I agree that the last.fm example should probably fall back to the exact variant automatically if annoy isn't installed.

Also I believe windows support with annoy might work now, but I'm thinking of transitioning the approximate nearest neighbours support over to [nmslib](https://github.com/searchivarius/nmslib) since its significantly faster.

**Comment by benfred** [comment]
I've changed to only try importing annoy right before the index is created here: https://github.com/benfred/implicit/pull/51 This warning shouldn't show up anymore. (I've also added code for nmslib/faiss as part of that PR which is worth checking out).
