### ISSUE TITLE
Rewrite model.recommend() to not require the user_items matrix that was already used in model.fit()?

### ISSUE THREAD

**Issue by chillerobscuro** [benfred/implicit#472]
I'm referring to the use case in the docs:
```
model = implicit.als.AlternatingLeastSquares(factors=50)
model.fit(item_user_data)
user_items = item_user_data.T.tocsr()
recommendations = model.recommend(userid, user_items)
```
In this case `user_items` is the same ratings matrix used to `fit()` the model, but transposed. It is not required if we set `filter_already_liked_items` to false, but in the case we do want that filtering, couldn't we pass an argument like `save_already_liked_items` to `model.fit()`, and then call `model.recommend()` without needing to pass the same matrix?
This would be useful in production settings, where fitting the model and generating the recommendations happen in separate contexts.

I'm sure there's already been some thought given to this, but if there is interest and some comments on structure I would be happy to try my hand at a pull request with this improvement.

**Comment by benfred** [comment]
Yeah - this is a legacy of how this library was written. The first version only handled training , and didn't have methods like recommend. 

When adding recommend I noticed that the only efficient way of doing this was to be passed a user_items matrix, when the fit method already worked on a item_users. I've been thinking of changing the fit methods to accept a user_items matrix to match since then.

I'd rather not change the model.recommend code here though: we'd have to transpose the matrix as the first step to collect all the liked items for the user - and this would be slow given that we can call model.recommend repeatedly.

**Comment by benfred** [comment]
I'm making this change as part of #481 - the model.fit and model.recommend methods will both take a user_items matrix after this change.
