### ISSUE TITLE
implicit.gpu._cuda.Matrix object has no attribute dot 

### ISSUE THREAD

**Issue by acho98** [benfred/implicit#497]
Hi~
When dot operation is performed to evaluate the model trained using implicit.als.AlternatingLeastSquares , the following error occurs

AttributeError: implicit.gpu._cuda.Matrix object has no attribute dot

The evaluation code includes below

         user_id = customer_id_map[customer_id]
         user_vector = model.user_factors[user_id]
         scores = item_vecs.dot(user_vector)
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Error
         top_k_item = np.argpartition(scores, -k)[-k:]

**Comment by benfred** [comment]
I don't think that evaluation code snippet you pasted is from this package? One of the things we're doing recently is moving towards doing inference on the GPU as well as training - meaning that the user_factor/item_factors matrices on the model aren't numpy arrays anymore on the GPU models.  

You can calculate recommendations for users on this by using 'model.recommend' though. Is there a reason you aren't using this instead of writing your own code?

If you want to write the recommend code yourself, you can convert the factors to numpy arrays by calling ```model.item_factors.to_numpy()``` . This will be orders of magnitude slower than doing the recommendations on the GPU though.
