### ISSUE TITLE
Add a recommend method for making customised recommendation for users?

### ISSUE THREAD

**Issue by vnnw** [benfred/implicit#5]
To compute similar artists is great, but making customised recommendation for each user based on his or her listening history could be better?

**Comment by benfred** [comment]
I agree that adding something like this to the library makes a ton of sense. I'll see about adding this when I have some time.

In the meantime:

``` python
def predict(item_factors, user_factors, userid, N=10):
        scores = item_factors.dot(user_factors[userid])
        best = numpy.argpartition(scores, -N)[-N:]
        return sorted(zip(best, scores[best]), key=lambda x: -x[1])
```
should return the top N artists  for userid.

**Comment by GuoleiSun** [comment]
Hi Benfred,
I think there is a problem in your code. You said cui is confidence matrix, whose elements should all be positive. And in this line:'' for i, confidence in nonzeros(Cui, u)'', you use cui as pu, which should be sparse. 
And in your example, I think you didn't differentiate bm25_weight(plays) with confidence matrix because you simply use bm25_weight(plays) as confidence matrix. 
Thanks for your code and achieved speed-up. But I don't think your implementation is the correct version of implicit feedback dataset in paper: http://yifanhu.net/PUB/cf.pdf

**Comment by benfred** [comment]
I'm pretty sure that the code correctly implements the paper.

Pui is a binary value - its 1 if the user has interacted with an item and 0 otherwise. The Cui confidence matrix I'm passing in is a sparse matrix, with entries for only the positive preferences (Pui = 1). So iterating over the nonzeros of Cui means that Pui is 1 . If I listed it out explicitly the code would be:

```python
        for i, confidence in nonzeros(Cui, u):
            factor = Y[i]
            A += (confidence - 1) * np.outer(factor, factor)
            Pui = 1
            b += confidence * factor * Pui
```
But since its just adding in a multiply by 1 - I don't need to do this.

Also Cui can be set to any weighting scheme you want - it doesn't affect how the solution is derived (since its a constant wrt to the params we're minimizing). The original paper suggests using the log of the play counts.

**Comment by benfred** [comment]
@vnnw the last  commit refactors this to a class, with a recommend method for generating personalized recommendations: https://github.com/benfred/implicit/commit/8c18f162118f794bd3859aa688ab46092d6667da#diff-604d1b48a6ae71b2cc39b27249942f12R84

In addition to the snippet I posted above, this also filters out the users own liked items.

**Comment by chapleau** [comment]
@benfred Just to make sure I get this right, when you say "Cui can be set to any weighting scheme you want", we're still assuming here that "empty" entries in the confidence matrix have a value set to exactly 1, right ?
