### ISSUE TITLE
Error: cuda extension is built, but disabling gpu support because of '{e}'

### ISSUE THREAD

**Issue by caijunjieNick** [benfred/implicit#558]

**Comment by benfred** [comment]
Usually this warning is set because you don't have a GPU installed, but you have a valid CUDA toolkit. If you don't have CUDA/cublas etc you shouldn't see this warning at all , and GPU support will just be disabled.

You can filter out this warning by running `warnings.filterwarnings("ignore", module="implicit.gpu")` in your code
