### ISSUE TITLE
BUG: Bayesian Personalized Ranking Sparse Matrix Demands sorted indices

### ISSUE THREAD

**Issue by GitDoctor1996** [benfred/implicit#576]
I have a sparse matrix that I am using and it works fine with the alternating least squares method. However, in the Bayesian Personalized Ranking method, I get this error: 

Input In [15], in <cell line: 8>()
      6 # Bayesian Personalized Ranking
      7 sh_bpr_model = implicit.bpr.BayesianPersonalizedRanking(factors = 50, regularization = 0.01, dtype = np.float64, iterations = 50)
----> 8 sh_bpr_model.fit(sh_freq_cust_mat * 40)
     10 # Logistic Matrix Factorization
     11 sh_lmf_model = implicit.lmf.LogisticMatrixFactorization(factors = 50, regularization = 0.01, dtype = np.float64, iterations = 50)

File bpr.pyx:149, in implicit.cpu.bpr.BayesianPersonalizedRanking.fit()

File ~/.local/lib/python3.8/site-packages/scipy/sparse/base.py:691, in spmatrix.__getattr__(self, attr)
    689     return self.getnnz()
    690 else:
--> 691     raise AttributeError(attr + " not found")

AttributeError: has_sorted_indices not found

I am sure this must relate to the configuration of Scipy, but I have looked all over the internet and cannot find a replicated use case. Can someone help me make sense of this as soon as possible?

**Comment by benfred** [comment]
thanks for raising! Both the BPR model expects a CSR matrix - which have the `has_sorted_indices` method on it. However, the ALS model converts to CSR if you pass in some other kind of sparse matrix : https://github.com/benfred/implicit/blob/f9050ae6340fbd549cf915dbf6e96a2ed713bac0/implicit/cpu/als.py#L121-L126

and right now the BPR/LMF model doesn't have this kind of conversions. I will add a fix to automatically convert this soon.

In the short term, can you try going `sh_bpr_model.fit(sh_freq_cust_mat.tocsr())` instead of `sh_bpr_model.fit(sh_freq_cust_mat)` ?

**Comment by GitDoctor1996** [comment]
I wound up figuring out that converting from a sparse matrix to a csr matrix was the way to go so now the script runs fine. Thank you.

**Comment by benfred** [comment]
I have a PR here https://github.com/benfred/implicit/pull/578 that will both accept non-csr input to the BPR/LMF models - and also warn that these methods expect CSR inputs. Hopefully this will make it clearer in the future
