### ISSUE TITLE
recommend_all() function  keeps cpu usage on 100% during recommendation. 

### ISSUE THREAD

**Issue by hemmat1991** [benfred/implicit#625]
i try use recommend_all() function over 10 million data. during the prediction, the CPU usage was 100% But hopefully, the process did not kill by the OS. is there any solution to reduce the CPU usage?

**Comment by benfred** [comment]
Depending on the size of your dataset, getting recommendations for all users can be quite expensive. This is because for each user, it has to calculate the scores for each item - and then return the top K best items for that user. For many datasets generating the recommendations will be much more expensive than training the model

There are some approaches to speed this up:
* You can look at using the approximate nearest neighbours integrations https://www.benfrederickson.com/approximate-nearest-neighbours-for-recommender-systems/ 
* Using the GPU code will lead to a massive speedup
* You can sample the items or the users you are recommending for
