### ISSUE TITLE
movielens.py MemoryError

### ISSUE THREAD

**Issue by dsun9** [benfred/implicit#64]
Non issue, it was 32-bit python, after installing 64-bit, it works fine

  File "pandas\_libs\parsers.pyx", line 894, in pandas._libs.parsers.TextReader.read
  File "pandas\_libs\parsers.pyx", line 944, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas\_libs\parsers.pyx", line 2228, in pandas._libs.parsers._concatenate_chunks
MemoryError

**Comment by dsun9** [comment]
my bad without due diligence. upon further looking, it seems it happens only with larger file. however, the file is 500ish MB and I have 16 gb with 8gb free on my laptop. any configuration?

**Comment by benfred** [comment]
The movielens 20m example only uses about 1.3 GB of memory on my system - I'm not sure why you are running out of memory =( 

It looks like you are using a 32 bit version of python though (Python36-32 in your path).  I wonder if its running out of addressable space (like I can see potential issues if you only have 4GB addressable memory because of the 32 bit python install, and this example needs a sizeable fraction of that in one contiguous chunk).

Can you try again with a 64 bit version of python? Maybe install anaconda ?

**Comment by dsun9** [comment]
Thanks Ben. you are right. it is running good now
