### ISSUE TITLE
module 'implicit.cuda' has no attribute 'CuCSRMatrix'

### ISSUE THREAD

**Issue by 3mei** [benfred/implicit#67]
Ben, thank you for a wonderful blogpost on CUDA programming! Was playing with the latest version of implicit. While the package does build, I am running into the `module 'implicit.cuda' has no attribute 'CuCSRMatrix'` error. 

It looks like this is due to the `implicit.cuda.CuCSRMatrix` call (and other related calls) on https://github.com/benfred/implicit/blob/master/implicit/als.py#L171. Switching all of them to `_cuda.CuCSRMatrix` after changing the import statement to `from implicit.cuda import _cuda` fixes the issue.

Note that https://github.com/benfred/implicit/blob/master/implicit/cuda/__init__.py#L3 doesn't seem to be doing what it's expected to do.

**Comment by benfred** [comment]
I can't replicate this problem - it works for me on both python v2.7 and v3.6 on my linux box =(. What version of python are you using?

**Comment by Vslira** [comment]
had the same issue, found the problem: When cloning the repo as pip install git+https:repo, the directory implicit/cuda had no __init__.py. Manually adding it and its contents from  https://github.com/benfred/implicit/blob/master/implicit/cuda/__init__.py fixed the problem here.

Btw, thanks @benfred for the great work!

**Comment by benfred** [comment]
thanks @Vslira ! I managed to replicate the problem here, I think that last commit should fix.
