### ISSUE TITLE
Out of Memory Error during using recommend for all users

### ISSUE THREAD

**Issue by Escape142** [benfred/implicit#688]
**Bug Report Summary:**

I encountered an Out of Memory Error while attempting to recommend all items to all users, which is a critical step in calculating item ranks for further metric calculations. To address this problem, I initially attempted batch calculations on an NVIDIA A100-SXM-80GB GPU but still faced the same issue. Consequently, I switched to using the CPU. However, even the CPU memory proved insufficient to handle the task. It seems that the problem is related to memory usage.

**Steps to Reproduce:**
I attempted to mitigate the issue by implementing batch recommendations as follows:

# Extract number of users and items
        userids, items = train_interactions.shape

        # Get the maximum number of non-zero test set
        max_items = test_interactions.getnnz(axis=1).max()

        # Use batches
        batch_size = 1024
        start_idx = 0
        ranks = np.empty((0, max_items), dtype="int32")

        # get an array of userids that have at least one item in the test set
        to_generate = np.arange(userids, dtype="int32")
        to_generate = to_generate[np.ediff1d(test_interactions.indptr) > 0]

        start_time = time.time()

        with tqdm(
            (len(to_generate) + batch_size - 1) // batch_size,
            desc="Generating recommendations", unit="batch"
        ) as pbar:
            while start_idx < len(to_generate):
                batch = to_generate[start_idx : start_idx + batch_size]

                # make recommendations on cpu due to large datasets
                if isinstance(
                    self.model,
                    (implicit.gpu.als.AlternatingLeastSquares, 
                    implicit.gpu.bpr.BayesianPersonalizedRanking)
                    ):
                    self.model = self.model.to_cpu()
                else:
                    pass

                ids_batch, _ = self.model.recommend(
                    batch, train_interactions[batch], N=items
                )
                start_idx += batch_size

                ranks_batch = self._implicit_recommendation_to_rank(
                    ids_batch, max_items, test_interactions[batch].toarray()
                )
                # Concatenate the new array to the result_array
                ranks = np.concatenate((ranks, ranks_batch), axis=0)

                pbar.update(1)

**Desktop:**
Operating System: Linux (Please specify the exact distribution if relevant)
implicit Version: 0.7.1
Python Version: 3.9.17
Cython Version: 0.29.26
cudatoolkit Version: 11.2

**Comment by benfred** [comment]
How many users and items are you generating recommendations for ?  It's possible that you're just blowing out of the memory on just storing the results. You'll need something like `8 * number_of_users * N` bytes of memory available for recommending items for all users - which could easily be happening here since you're setting `N=items` (like if you have 100k users and 100K items , asking for N=100K will use 80GB of memory just for the results).

Also, is there a reason that you're returning all the items for each user? This is expensive to do, and usually you will only need to the top items (so like `N=100` or something instead of all the items): if you're using this for serving results to users they won't see items past a certain limit, and if you're doing evaluation I'd recommend using something like MAP@K. If you have 100K items that you're ranking, reducing N from 100K down to 100 will reduce memory consumption by 1000x.

Also, implicit does batching internally for both CPU and GPU models to manage memory - so you won't gain anything by writing your own batching code.

**Comment by Escape142** [comment]
I have varying numbers of users, ranging from 1,000 to 1 million. My objective is to obtain rankings for items for each user, which I then use to calculate my quality and diversity metrics. This is why I employ the parameter N=items. To manage memory usage and prevent Out of Memory Errors, I currently employ batch predictions. However, I'm encountering memory issues over time, and it's accumulating like a cache. Are there alternative methods for obtaining rankings for all items using Implicit?

Thank you in advance.

**Comment by benfred** [comment]
> However, I'm encountering memory issues over time, and it's accumulating like a cache.

Do you see this behaviour if you comment on this line `ranks = np.concatenate((ranks, ranks_batch), axis=0)` in that batching code you pasted above?   I'm guessing that you're just running out of memory from accumulating the results, since they can be very large when ranking all the items.

If you still see an OOM with that line commented out,  can you try running a memory profiler to figure out what the hotspot is here? (something like https://github.com/pythonspeed/filprofiler ). fwiw, implicit shouldn't be using an increasing amount of memory over time.

>  My objective is to obtain rankings for items for each user, which I then use to calculate my quality and diversity metrics. 

Do you need to rank all the items for these metrics? For quality metrics, how about using something like MAP@K or NDCG@K (where K << number_of_items). 

If you absolutely need to rank all items, you might need to stream the results (like calculate the metrics per batch, and then aggregate at the end).

**Comment by benfred** [comment]
going to close this - feel free to re-open if you're still having issues
