### ISSUE TITLE
Memory problem

### ISSUE THREAD

**Issue by Keith-shu** [benfred/implicit#69]
I tried the example script with movielens 20M data set (ratings.csv is about 500M) on my computer and I encountered memory error. my OS is centos7 with 8GB RAM. and I was running "top" command while running this example only to find my memory was almost fully used.

Is this a common problem or 8GB RAM is just not enough?

**Comment by benfred** [comment]
On my system, the movielens 20m example takes about 1.3G to run - so you *should* be able to run it.

However, there was another person having a similar problem - https://github.com/benfred/implicit/issues/64 . I believe the problem was that they were using a 32 bit version of python, and switching to a 64 bit version of python worked. What does your python install look like?

**Comment by Keith-shu** [comment]
Actually I'm not very sure :). I first tried with default python version on Centos. Then I RTFMed the problem and they told me to try with a 64bit version of python.then I Downloaded the latest python source release (for linux) and tried again but it didn't work. 

It looks like this:
Python 2.7.14 (default, Nov 28 2017, 18:55:14) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2

you see,I just don't know  is this a 32bit version or 64 bit version?

**Comment by benfred** [comment]
Can you try with the anaconda 3 install ? https://conda.io/docs/user-guide/install/index.html we can be guaranteed of a 64 bit install then . Also anaconda bundles intel mkl blas libraries - which are faster than the openblas alternatives.

**Comment by Keith-shu** [comment]
I tried with anaconda install and it didn't work :). maybe it's because I'm using python2.7 and I should try with python3. Anyway, thanks!
