### ISSUE TITLE
getting different results when reinitializing the model with same parameters

### ISSUE THREAD

**Issue by snoecko** [benfred/implicit#96]
I'm getting completely different recommendations when reinitializing the ALS-model with the same parameters. 

after setting up the csr matrix I do:

`model = implicit.als.AlternatingLeastSquares(factors=50)
`

```
model.fit(item_user_data)
user_items = item_user_data.T.tocsr()
recommendations = model.recommend(userid, user_items)
```

Now when I run the `model.fit` part again, i get nearly the same results but with different predictions (which is reasonable). But when I reinitialize the ALS-Model with the exact same parameters I get completely different results. 

```
model = implicit.als.AlternatingLeastSquares(factors=50)
model.fit(item_user_data)
user_items = item_user_data.T.tocsr()
recommendations = model.recommend(userid, user_items)
```

Why is that?

**Comment by benfred** [comment]
The initial factors are initialized randomly - and I'm guessing in your case this is causing it to converge to a different solution. If the factors are already initialized, the model won't re-initialized to random on fit - so when calling 'fit' repeatedly on the same model you won't see radically different results.

When you call 'recommend' - what score values are you seeing? In most casing the solutions should be pretty similar after calling fit. It might be worth trying to tune the confidence values passed as an input, potentially by multiplying the confidence weights by a constant (alpha) before calling fit.

You should probably by determining the best value of alpha via cross validation - but a useful heuristic to get started is it to set the alpha param such that the positive examples and negative examples have  equal weight:

```python
Riu = item_user_data
alpha = (Riu.shape[0] * Riu.shape[1] - Riu.nnz) / sum(Riu.data)
model.fit(alpha * Riu)
```

since all the zeros in the matrix (negative examples) get a default confidence of 1.

**Comment by snoecko** [comment]
thank you very much! that helped a lot! i tried a alpha value of 40 or 50 - your calculation lead to a value of 0.001
